### ISSUE TITLE
Automatically highlights the first row option after typing parameter?

### ISSUE THREAD

**Issue by YogaHadiN** [truckingsim/Ajax-Bootstrap-Select#100]
Is there a way how to make the first row option highlighted after typing parameter?  So I can just press tab right after the option shows on first row, (with selectOnTab option set on true in selectpicker option)

It think this is default on selectpicker without ajax

Btw.. this plugin in is wonderfull.. great job..

**Comment by markcarver** [comment]
This really falls outside the scope of this project. There are already events and callback functions you can utilize to customize something like this to your liking.
