### ISSUE TITLE
problem when filter the letter ñ 

### ISSUE THREAD

**Issue by juanmarinelli** [truckingsim/Ajax-Bootstrap-Select#104]
Hello, i have a problem with de plugin when filtring the letter ñ.
 when i put "ñ" the result is "no results"

Someone could tell me how to solve it??
thanks and sorry for my inglish

**Comment by truckingsim** [comment]
@juanmarinelli ajax bootstrap select doesn't actually do the filtering your server does.  Have you checked the response from the server and debugged there?

**Comment by juanmarinelli** [comment]
Thanks for the answer. Yes, the response from the server is ok.  I think that the problem is in the contenType in AJAX when send the parameters POST or in some function in ajax-boostrap-select.
But in te example I put a word with ñ and work ok. 
When the data with come from the server i put utf8_encode() and utf8_decode() but nothing. an example with ñ in the database is UREÃ‘A when realy is UREÑA

**Comment by juanmarinelli** [comment]
![captura de pantalla 2017-01-23 a las 11 16 11](https://cloud.githubusercontent.com/assets/22064976/22207327/7a764d0e-e15d-11e6-98b4-5151a9b0e3bb.png)
![captura de pantalla 2017-01-23 a las 11 16 25](https://cloud.githubusercontent.com/assets/22064976/22207328/7a7f147a-e15d-11e6-9391-bc8d9ab1a852.png)

**Comment by truckingsim** [comment]
@juanmarinelli can you see what is being sent to the server?  Maybe Ajax Bootstrap Select is mangling the letter when sending it to the backend?

You should be able to view the request in the network panel and see what is going up, if you can show me that, it would be helpful.

**Comment by markcarver** [comment]
This project doesn't manipulate user provided data in any way:

It retrieves the raw value:
https://github.com/truckingsim/Ajax-Bootstrap-Select/blob/master/src/js/classes/AjaxBootstrapSelect.js#L299

And then stores the raw value:
https://github.com/truckingsim/Ajax-Bootstrap-Select/blob/master/src/js/classes/AjaxBootstrapSelect.js#L332-L334

This is most definitely a server side issue.
