### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by fadstir** [truckingsim/Ajax-Bootstrap-Select#106]
Hey. I'm new to web development with only a little bit experience with JQuery and Bootstrap. What are the steps to extend Bootstrap select to use your library? I've cloned the library into my local machine, but want to test using sample HTML.

**Comment by truckingsim** [comment]
@fadstir you can see how to use it here: https://github.com/truckingsim/Ajax-Bootstrap-Select/blob/master/example/php/index.php#L72-L106

There's also this fiddle: https://jsfiddle.net/jefffan24/okbnumdc/ 

Which works with a static dataset and does the filtering on the client side.

**Comment by fadstir** [comment]
Thanks @truckingsim I'll take a look at this.

**Comment by truckingsim** [comment]
@fadstir gonna close this since there isn't an actual issue here let us know if you run into anything specific.
