### ISSUE TITLE
Is it possible to initialize with all results?

### ISSUE THREAD

**Issue by marianopeck** [truckingsim/Ajax-Bootstrap-Select#107]
Hi,

I would like to be able to initialize the bootstrap select with all the results as what would happen with Bootstrap Select alone, but with the difference of using this ajax-based search. Right now, when[ I am trying this plugin](http://jsfiddle.net/jefffan24/okbnumdc/)  it's more like "autocomplete" where no option appears until I make the search. In my case, I want to present all results, but also allow further search. How can I initialize it that way?

Thanks in advance,

**Comment by truckingsim** [comment]
You would need to have the results in the select on the html sent down from the server.  Then do the initialization like you are now.
