### ISSUE TITLE
Cannot instantiate an AjaxBootstrapSelect instance without selectpicker first being initialized!

### ISSUE THREAD

**Issue by yurik94** [truckingsim/Ajax-Bootstrap-Select#108]
I'm trying to use this awesome plugin in a BS modal but I got this:

> Cannot instantiate an AjaxBootstrapSelect instance without selectpicker first being initialized!

a piece of code:

` selectPartner = jQuery('.select-partner');
        selectPartner.selectpicker({
            bindEvent: 'keyup paste'
        }).ajaxSelectPicker({`

I've tried wrapping 'ajaxSelectPicker' in a setTimout and it seems to work.

**Comment by truckingsim** [comment]
can you do a `selectPartner.length` for me after setting it but before running `.selectpicker()`.

**Comment by yurik94** [comment]
Now it seems to work even if the error is thrown:

```
jQuery(document).ready(function () {

        var selectPartner = jQuery('.select-partner');
        selectPartner.selectpicker({
            bindEvent: 'keyup paste',
            liveSearch: true
        });

        selectPartner.on('changed.bs.select', function (a, b, c, e) {
            if (b != undefined) {
                alert('index = ' + b);
                alert('value = ' + jQuery('#partner').find('option').eq(b).val());
            }
        });
        
        setTimeout(function () {
            selectPartner.ajaxSelectPicker({
                ajaxOptions: {
                    url: '/api/partners',
                    dataType: 'json',
                    headers: {
                        'X-CSRF-Token': window.Laravel.csrfToken
                    },
                    data: function () {
                        return {
                            partner_name: selectPartner.find('div.bs-searchbox > input').val()
                        };
                    }, beforeSend: function (xhr, opts) {
                        if (selectPartner.find('div.bs-searchbox > input').val() < 3) {
                            xhr.abort();
                        }
                    }
                },
                emptyRequest: true,
                locale: {
                    emptyTitle: 'Ricerca partner&hellip;'
                },
                preprocessData: function (data) {
                    console.info('data', data);
                    if (data.partners != null)
                        return data.partners;
                    return [];
                },
                preserveSelected: false
            });
        }, 500);
    });
```
I'm using Laravel 5.4 as backend, last version of Bootstrap, Bootstrap-select and jQuery 3.1.1.

![image](https://cloud.githubusercontent.com/assets/13189646/23806671/d7c569ca-05c2-11e7-9bcb-f7fc10da9c61.png)

While taking this screenshot (adding 'debugger') I didn't get the error but.... I can't see the data sent in the request :(

**Comment by truckingsim** [comment]
@yurik94 I get that error when `livesearch: true` is used.  Try removing that and see if it still works.

**Comment by truckingsim** [comment]
It should work without that property as seen here: https://jsfiddle.net/jefffan24/okbnumdc/

**Comment by yurik94** [comment]
removing setTimeout and livesearch property didn't helped me, the request body is empty....

**Comment by truckingsim** [comment]
Removing livesearch will fix the error from ajaxbootstrap select, I would also try removing the bindEvent as well.  AjaxBootsrapSelect takes over the input completely, passing any settings to bootstrap select may be messing with it.

**Comment by yurik94** [comment]
Victory! 👍 
Even though I use the updated version of all the dependecies it is working perfectly now, really thanks for your great work!

**Comment by yurik94** [comment]
Although it is working I get again the error message on **any subsequent** refresh of the page after I force reload (empty cache) the page :(

**Comment by truckingsim** [comment]
Are loading ajax bootstrap select after bootstrap select? (Like the JS files, not the function calls).

**Comment by yurik94** [comment]
Did you mean this?

![image](https://cloud.githubusercontent.com/assets/13189646/23826738/458f5052-06a3-11e7-93fa-52f9e5674b9f.png)

**Comment by truckingsim** [comment]
Yeah that's what I meant....so that's not it.

I'll keep trying to think of reason this is happening, right now I don't have anything else.  Let me know if you get this working, I'm curious.

**Comment by truckingsim** [comment]
@yurik94 any update on this.  I don't have any new ideas, curious if you got it working.

**Comment by yurik94** [comment]
The error message is still appearing in the console if I enable caching, btw the plugin is working perfectly so idk!

![image](https://cloud.githubusercontent.com/assets/13189646/24479455/b7e758b2-14df-11e7-90ff-9eca8945ca15.png)

**Comment by pinar-kaya** [comment]
Use id instead of using class for selection of component. That is;
selectPartner = jQuery('#component-id');

**Comment by dmazilov** [comment]
There is option to use $("select.<your-class>"), not only id. It works in my case.

**Comment by pranay16** [comment]
@dmazilov 's solution works perfectly.

The reason we were seeing that error was because we call this function multiple times....
First time, $(".your-ajax-select-class")... works just fine.

However, selectpicker puts the same class on the div it creates around the <select> for its own display

Now the next time we do $(".your-ajax-select-class")... It tries to add ajaxselectpicker to the div and it fails.

Hence, $("select.your-ajax-select-class") solves the issue

**Comment by pranay16** [comment]
> Removing livesearch will fix the error from ajaxbootstrap select, I would also try removing the bindEvent as well. AjaxBootsrapSelect takes over the input completely, passing any settings to bootstrap select may be messing with it.

How do you search for option then?

**Comment by ppazos** [comment]
still getting this error and actually need to apply the select picker on a class not an ID, this is on v1.4.4 @truckingsim @markhalliwell
