### ISSUE TITLE
Custom function to load data

### ISSUE THREAD

**Issue by comodore31** [truckingsim/Ajax-Bootstrap-Select#111]
Is there a way to define its own function to load data like
$('.selectpicker').selectpicker().ajaxSelectPicker({
    data: function (data) {
// my function here
        return ['1', '2']; // ...
    }
});
This could be done in AJAX mode, filtering among 100000 values.

**Comment by truckingsim** [comment]
depends on what you mean by load data.

https://jsfiddle.net/jefffan24/okbnumdc/ shows how to process data from the server on the client (it does the filtering client side and just loads a static list).

You can do what you did there to dynamically build the data sent to the server.

You can't override the ajax calls themselves though.  What are you trying to do exactly?

**Comment by comodore31** [comment]
Actually there is an existing web service filtering data not using q as parameter and returning data not not well formatted for ajaxselectedpicker.
Anyway, is it possible to just call my function, passing q as parameter and returning the 10 first values filtered

**Comment by truckingsim** [comment]
@comodore31 do you still need help?

**Comment by comodore31** [comment]
No thanks, I did my own version of bootstrap select to do the job :)
