### ISSUE TITLE
Unable to change options.ajax data dynamically

### ISSUE THREAD

**Issue by vibs2006** [truckingsim/Ajax-Bootstrap-Select#134]
I have two dropdowns. 
First dropdown contains the database name from which I want to display the dropdown data. 

I initialize ajax-bootstrap-select using `$('#ajax-select-multiple').selectpicker().ajaxSelectPicker(options);` 

I added another variable in  **options.ajax.data**.databaseType along with default **'q'**. 
Though q updates but that is not the case with  options.ajax.data.databaseType. Now the surprising thing is that if i console.log(options.ajax.data.databaseType) then I see the updated value but that thing is not posted in query. Please help by telling how to **Properly reintialize ajax-select-picker with a new options data**

**Comment by truckingsim** [comment]
Data can be a function.  You'll need to define data as a function and return an object.  If data is a function it will be called with each ajax request.

**Comment by 0x0010** [comment]
Hi five, I solved this by modifying some code and adding some features.
first,
add code to AjaxBootstrapSelectRequest function before invoking the ajax request.
````javascript
//append data dynamically
if (this.options.extendData) {
  var ed = this.options.extendData;
  var edl = this.options.extendData.length;
  for (i = 0; i < edl; i++) {
    this.options.data[ed[i].key] = ed[i].func()
  }
}
// Invoke the AJAX request.
this.jqXHR = $.ajax(this.options);
````
second, let's talk about how to use
````javascript
ajax: {
  contentType: "application/json;charset=UTF-8",
  url: $.serviceUrl.appCenter.list,
  type: 'POST',
  dataType: 'json',
  // Use "{{{q}}}" as a placeholder and Ajax Bootstrap Select will
  // automatically replace it with the value of the search query.
  data: {'name': '{{{q}}}'},
  extendData:
    [
        {
          key: "hello",
          func: function() {
              return $("#ddal-app-name").val();
            }
        }
    ]
},
````
add extendData to ajax body, then all the objects<k,v> will be append to ajaxData after executing func dynamically before sending to server.

I hope this will help.

**Comment by dropskie** [comment]
Thx 0x0010 I've been trying to figure this out for hours. Your code has saved my life. 
I changed my initialisation to call a function:

` extendData:
                    [
                        {
                            key: "id",
                            func: function () {
                                return myobject.GetSelectedValue();
                            }
                        }
                    ]`
