### ISSUE TITLE
How to set dropdown size? and statusToShort doesn't work

### ISSUE THREAD

**Issue by Luca4k4** [truckingsim/Ajax-Bootstrap-Select#137]
Hi, I have a database with 8k+ rows, I'm implementing an asyncronous select  to choose which city to select with your awesome plugin. But with low letters number (two) my page become very long because Bootstrap-select's option "size" stop working when i use your plugin. Is there a solution to this problem?
Also i want to signal that locale.statusToShort property doesn't seem to work.

Good sunday at all :)

**Comment by truckingsim** [comment]
For your second question: It should be `statusTooShort` the docs on the front page is wrong sorry.
For your first question I need a little more info.

**Comment by Luca4k4** [comment]
Thank you for the answer
`statusTooShort` worked, I was a little stupid to doesn't see that! :/

For my first question, this is my code:
`$('#mySelect').selectpicker({
                            size: 6,
                            ..
                        })
                        .ajaxSelectPicker({
                            minLength: 2,
                            ajax: {
                                 ....
                            },
                            
                            locale: {
                                     ..      
                             }
                        });`

The option "size: 6" doesn't work. When I do a search I see a very long list of items and my page become very long, the scrollbar doesn't appears after the sixth item

**Comment by truckingsim** [comment]
We don't control the render of the dropdown, selectpicker does.  We just refresh the select picker after changing the options.  So I'm not sure why that isn't working.  Does it work without ajax-bootstrap-select?

**Comment by Luca4k4** [comment]
Yes, without it works. 

[Here](https://imgur.com/a/hI0Nm) there is a screenshot. This happens with size:6 as the code reported above. Do you have any suggestions?

**Comment by danielvoicu** [comment]
I am having the same issue as @Luca4k4. If I only use selectpicker, size seems to be working.

I've tried with data attributes and with javascript options, still can't control the size of the list.

**Comment by PhilPJL** [comment]
If it's any help I don't use size but I do use data-window-padding

                        <div class="col-sm-4">
                            <select name="@Html.NameFor(m => m.UserUniqueId)"
                                    id="@Html.IdFor(m => m.UserUniqueId)"
                                    class="form-control selectpicker" 
                                    data-live-search="true" 
                                    data-window-padding="[50,0,50,0]">
                                @foreach (var option in Model.Users)
                                {
                                    <option value="@option.Value"
                                            data-icon="@option.DataIcon"
                                            data-subtext="@option.DataSubText"
                                            selected="@(Model?.UserUniqueId.ToString() == option.Value)">
                                        @option.Text
                                    </option>
                                }
                            </select>
                        </div>


                $('#@Html.IdFor(m => m.UserUniqueId)').selectpicker();
                $('#@Html.IdFor(m => m.UserUniqueId)').ajaxSelectPicker({
                        ajax: {
                            url: '@Url.Action("GetUsersJavaScriptArray")',
                            data: function () {
                                var params = {
                                    q: '{{{q}}}'
                                };
                                return params;
                            }
                        },
                        cache: false,
                        locale: {
                            emptyTitle: '@Resources.SearchForUser...',
                            statusSearching: '@Resources.SearchingForUser...',
                            statusTooShort: '@Resources.MinCharsRequired'
                        },
                        minLength: 3,
                        preserveSelected: false
                    });

Works great

**Comment by Sylvio84** [comment]
Hi, I meet this bug too. On click the list is too long and is not limited to the number of items specified in Bootstrap Selectpicker plugin. After closing and reopening the select picker, it works fine and the number of items displayed is correct.

**Comment by MichaelGrabchak** [comment]
Just got the same issue with drop-down size. I fixed it by overriding the styles:

`.bootstrap-select > .dropdown-menu > .inner {
    max-height: 152px !important;
}`

Yeah, it is not the best idea to override some bootstrap styles but as a workaround, it works pretty well. The only disadvantage here is that you can't dynamically change the drop-down size.

**Comment by ne0c0de** [comment]
You saved my day @MichaelGrabchak , thank you so much
