### ISSUE TITLE
Match entire word when using livesearch

### ISSUE THREAD

**Issue by danielvoicu** [truckingsim/Ajax-Bootstrap-Select#138]
Hi,

I'm using bootstrap-select with livesearch, along with ajax-bootstrap-select, and I was wondering if there's a way to match the exact word. I've noticed that at this point there's "startsWith" and "contains" from bootstrap-select, but both of them tend to show the entire list of options. What should I do to fix this?

Thanks!

**Comment by markcarver** [comment]
So, this plugin essentially overrides/extends the `liveSearch` option from bootstrap-select. It doesn't actually care about what the `liveSearchStyle` option is set to though, it just uses makes a request to whatever backend server you want to do the actual matching (which you can match however you like).
