### ISSUE TITLE
Ajax-Bootstrap-Select breaks showContent and showSubtext by setting titles

### ISSUE THREAD

**Issue by psyon** [truckingsim/Ajax-Bootstrap-Select#142]
On line 136 of AjaxBootStrapSelectList.js, the title for each option is set to the text value.  Bootstrap-select always uses the title value if it is set.   The title should only be set, if it is passed from the data. 

The current code is:

    $option.val(item.value).text(item.text).attr('title', item.text);

And should be changed to 

    $option.val(item.value).text(item.text);
    if(item['title'] !== undefined) {
        $option.attr('title', item.title);
    }

**Comment by rino7** [comment]
Besides that, is necessary add the 'title' attr in line 54
https://github.com/truckingsim/Ajax-Bootstrap-Select/blob/f4869c3f2c8c2b4b187137cae281073456d3a8a6/src/js/classes/AjaxBootstrapSelectList.js#L54

**Comment by markcarver** [comment]
This was fixed in #179
