### ISSUE TITLE
XSS Vulnerability on Ajax-Bootstrap-Select

### ISSUE THREAD

**Issue by googlicius** [truckingsim/Ajax-Bootstrap-Select#144]
When clicked result dropdown list at the script tag record like this: '<script>alert('XSS attack!');</script>'
It show alert: 'XSS attack!'.

How can I fix this?

**Comment by truckingsim** [comment]
@googlicius We don't do the rendering of the dropdown, `bootstrap-select` does the rendering.  I would report this on there.

**Comment by googlicius** [comment]
@truckingsim The rendering is OK, the error occur when I click on the list at the option has script tag.

`bootstrap-select` does not have this error.
