### ISSUE TITLE
Selected item sub-text and icon not displayed

### ISSUE THREAD

**Issue by PhilPJL** [truckingsim/Ajax-Bootstrap-Select#149]
I'm initialising the select like so:

                // Initialise item picker
                var object = $('#@Html.IdFor(m => m.ItemName)');
                if (object !== null && object !== undefined) {
                    object.selectpicker();
                    object.ajaxSelectPicker({
                        ajax: {
                            url: '@Url.Action("GetItemsJavaScriptArray")',
                            data: function() {
                                var params = {
                                    q: '{{{q}}}'
                                };
                                return params;
                            }
                        },
                        cache: false,
                        locale: {
                            emptyTitle: '@Resources.SearchForItem...',
                            statusSearching: '@Resources.SearchingForItem...',
                            statusTooShort: '@Resources.MinCharsRequired'
                        },
                        minLength: 3,
                        preserveSelected: false
                    });
                }

Which works fine and we get a nice drop down like this

![image](https://user-images.githubusercontent.com/271656/36916593-41d4f086-1e4c-11e8-9fa3-3495dd628500.png)

However when I select one of the items, the sub-text and icon aren't displayed, just the text - as you can see in the image.

It should really look like:

![image](https://user-images.githubusercontent.com/271656/36916661-8528bbe2-1e4c-11e8-8498-0f7e2b7c1b53.png)

**Comment by truckingsim** [comment]
Does this happen with just straight bootstrap-select, not ajax-bootstrap-select?

**Comment by PhilPJL** [comment]
Yes it works fine for straight bootstrap-select.

**Comment by miki995** [comment]
Having same issues @truckingsim.
Before starting typing ( using ajax ) => http://i.imgur.com/2DQ1ZCU.png
After one single letter => http://i.imgur.com/NgYSRJB.png
Can we fix this?
 :D
