### ISSUE TITLE
problem with bootstrap 4

### ISSUE THREAD

**Issue by analcero** [truckingsim/Ajax-Bootstrap-Select#151]
after insert digits don't show the list of item.

**Comment by truckingsim** [comment]
Can you provide an example?  Its been a while since anyone has worked on this, I'm not surprised there's an issue with Bootstrap 4.

**Comment by fervi** [comment]
@truckingsim 
Maybe he has the same problem as me. If Bootstrap 4 is used, then the request is sent and probably received (Ajax), but it is not changed on the client side, so the client can not choose the right option.

I am talking about a situation in which we will only replace libraries with newer ones.

**Comment by truckingsim** [comment]
The problem is that our repo doesn't directly use any bootstrap.  We using jQuery's ajax to make the request, we change the actual underlying select element, and then call `refresh` on the bootstrap-select instance.  Bootstrap-select is not part of bootstrap.  I get there's a problem, but without having an example its hard to tell if this is on us or something else.

**Comment by fervi** [comment]
@truckingsim Yep, but Bootstrap-select is compatibile with Bootstrap 4. But maybe I have something in the code (I mean i just download Ajax Bootstrap Select code and change versions to newest)

http://194.28.50.88/ajax/example/php/index2.php

**Comment by truckingsim** [comment]
So `.dropdown-menu` is `display: none` for some reason.  That's why none of the options are showing.  We are rendering them, but the menu is hidden.  Did you upgrade the bootstrap-select version as well?  It may be doing something to the dropdown menu to make it visible in 4?

**Comment by fervi** [comment]
I will try to play, because even the menu on the left should display the results (as it does not use Ajax). However, in another project I use Bootstrap Select (the latest from Bootstrap 4) and no problems.

**Comment by truckingsim** [comment]
That's exactly why i asked :).  Let me know if you find anything interesting.

**Comment by henriqueiv** [comment]
Same issue here. Still not able to identify why `.dropdown-menu` is `display: none`. Also noticed that even when changing to `display: block` it works in the first time but when clicking again the search box is misplaced and nothing appears, seems to be breaking some CSS.

**Comment by reloxx13** [comment]
i have no problems with bs4.

use the dev branch of bootstrap-select.

this is a bs-select issue and not a bs-ajaxselect issue!

im on 1.13.3-dev bs-select, but there is now a 1.14-dev and official bs-4 support is announced. 

https://github.com/snapappointments/bootstrap-select/tree/v1.14-dev
