### ISSUE TITLE
Proper way to show selected items on edit form

### ISSUE THREAD

**Issue by jcrawford** [truckingsim/Ajax-Bootstrap-Select#152]
I have an edit form where values are already selected (multiple selections allowed), I currently have the system putting the <option> tags into the <select> element and in the js I am setting the 'val' with an array of values.  I am then calling refresh and .change();  

This works somewhat and shows the values as selected and I can search to select more.  The issue happens when I deselect one of the values that were there on page load.  It does not get removed from the currently selected group, the check mark goes away but the value remains.

Is there an example somewhere showing the proper way to implement this?

**Comment by RomanRabirokh** [comment]
@jcrawford 
Example?
this is a bug.
when the page is reloaded or loaded in select there is something deselect does not work

**Comment by jcrawford** [comment]
If you had replied sooner than almost a year later I could have replicated the issue, I have changed jobs and before leaving believe we went with a different component.

**Comment by RomanRabirokh** [comment]
@jcrawford 
I am not related to this plugin.
just ran into the same problem as you((

**Comment by jcrawford** [comment]
@RomanRabirokh my apologies I thought you were asking for a way to replicate the bug.  I am sorry that I cannot be of assistance, it appears the author of this plugin just overlooks issues for quite some time.

**Comment by RomanRabirokh** [comment]
@jcrawford  
it is open source, no support (

solves this problem
maybe someone will need.
https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/85#issuecomment-299838545

**Comment by truckingsim** [comment]
@jcrawford @RomanRabirokh I haven't used this in production in over 3 years.  Roman is right that, the comment he linked to fixes it, but it's not solving the actual problem which I have no clue why it happens.  I don't have the free time to look into why it happens.  If someone can look into and figure out why I would be open to trying to fix it, but with no help there I just don't have the time right now.

**Comment by markcarver** [comment]
This sounds like a dup of several issues/PRs.
