### ISSUE TITLE
Inner dropdown menu doesn't collapse for short results after long results

### ISSUE THREAD

**Issue by Folkman** [truckingsim/Ajax-Bootstrap-Select#156]
I believe this is a result of the `virtualScroll` option.  When a search with short results is made after a search with long results, the `ul.dropdown-menu.inner` maintains a `margin-top` and `margin-bottom` that corresponds to the large search results.  I've worked around it by setting the margin to 0 prior to populating the list with the `processData` hook.

```js
processData: function () {
  // Fixes issue with dropdown not collapsing after large search results
  this.plugin.$element.nextAll('.dropdown-menu')
    .find('ul.dropdown-menu.inner')
    .css({ margin: 0 });
}
```

**Comment by truckingsim** [comment]
If you want to make a PR with both this and your other issue I'll happily take a look.

**Comment by markcarver** [comment]
Closing in favor of PR
