### ISSUE TITLE
firefox mobile scroll-linked positioning effect problem

### ISSUE THREAD

**Issue by masteriii** [truckingsim/Ajax-Bootstrap-Select#163]
work well on pc but not working on Firefox mobile. 

debug tool:
Firefox WEB IDE

Error:
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Comment by truckingsim** [comment]
@masteriii does this happen when it's just regular bootstrap select?  We don't actually do that much rendering or changing how bootstrap-select works.  I'd be surprised if we are doing something to cause this and not the parent library.

**Comment by masteriii** [comment]
No problem when use only bootstrap select. Error when use with Ajax bootstrap select.

Test with:
FF lastest ver. (Android)
Google chrome lastest (iphone)

**Comment by markcarver** [comment]
This doesn't seem like it's an issue with this project.
