### ISSUE TITLE
Translations in Angular

### ISSUE THREAD

**Issue by miki995** [truckingsim/Ajax-Bootstrap-Select#165]
How does translations work, I passed langCode: 'fr-FR' and nothing happens?
Any explanation of it's usage.
@truckingsim

**Comment by truckingsim** [comment]
You need to load both the language file and the ajaxBootstrapSelect on the page for it to work.

**Comment by miki995** [comment]
Do you have example code, as I've already tried some, but no luck, sorry for bothering. Also having problems with ajaxSelectPicker, same issue with language...

**Comment by miki995** [comment]
Ok, found a way to load them in angular. If someone have problems as well he can read my post on Medium which I will make today [here](url)
