### ISSUE TITLE
Add Serbian Translation

### ISSUE THREAD

**Issue by miki995** [truckingsim/Ajax-Bootstrap-Select#166]
Hello, 
I want to add Serbian translation. I can't push to branch to make Pull Request. Can I get acess?
@truckingsim

**Comment by truckingsim** [comment]
@miki995 if you fork the repo, you can push to your fork and then make a PR from your fork to here.

Github has some documentation around this: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by miki995** [comment]
Thanks, I've figured it out aldready, earlier today. Will make it soon.
