### ISSUE TITLE
Feature request: ajax without livesearch

### ISSUE THREAD

**Issue by weha** [truckingsim/Ajax-Bootstrap-Select#171]
I would like the possibility to make an ajax call upon opening the dropdown from the select and populate it this way.
So no livesearch, just live data in the dropdown.
I know about #69 but I think my request is different as it should make the ajax call on open and not on document ready.
Secondly, if possible, maybe a shortlived / timed (ie: 10 seconds) cache to reduce the calls if the user is clicking a lot on the same select.

If this is possible with bootstrap-select it self, sorry for bothering you then but I can't seem to find anything about ajax in the documentation.
Loading it with separate code is probably not going to be a smooth experience.
Either way, I think this wouldn't difficult to implement as an option in your ajax version. :)

Thank you for the great work!

**Comment by StevenP94** [comment]
I agree, I need it too:
I need a new method that lauch an ajax data request for the current selected item, in this way I can preload the form and keep it ready for a modify..
Please give us an hint on how to implement this! I've added the method but can't find the plugin object to pass it to read the options

**Comment by markcarver** [comment]
So this plugin is basically an autocomplete in a dropdown. Removing that aspect would likely require a lot of refactoring. Not something I'd really care to do at the moment.

What you're asking for though, could be done easily using bootstrap-select's own [show.bs.select](https://developer.snapappointments.com/bootstrap-select/options/#events) event to initiate an ajax request and then manually update the options in the select element and invoke [.selectpicker('refresh')](https://developer.snapappointments.com/bootstrap-select/methods/#selectpickerrefresh).

FTR, that is essentially what this plugin does, but again it's coded more around autocomplete/typing.
