### ISSUE TITLE
Trigger search

### ISSUE THREAD

**Issue by LucaNitti** [truckingsim/Ajax-Bootstrap-Select#172]
There is a way to trigger search?
I need to programmatically trigger search event to reload some data without modify query. There i a way to do this?

**Comment by truckingsim** [comment]
@LucaNitti  If you don't override the bindEvent option you can try:

```
$('#selectId').data('AjaxBootstrapSelect').$searchbox.trigger('keyup');
```

I haven't tried this as I don't have this running anywhere on my machine at the moment.

**Comment by LucaNitti** [comment]
yes, it works, but there is a way to trigger search and and mantain selection?

In my project the user can search a value or can choose from one or two default value. When user select a default value (using checkbox), i need to setup the correct value on select, make a query to my backend to retrieve some data.

**Comment by markcarver** [comment]
Aside from triggering the `bindEvent` as suggested above, no.
