### ISSUE TITLE
jQuery .clone() support

### ISSUE THREAD

**Issue by rougin** [truckingsim/Ajax-Bootstrap-Select#2]
As I stated in the issue in https://github.com/silviomoreto/bootstrap-select/issues/606#issuecomment-45043448, it seems that the plugin doesn't work in cloning. I used the code in this issue https://github.com/silviomoreto/bootstrap-select/issues/605. After that, when I try to clone the selectpicker, it will not load all the data to the cloned item. But if I select one data to the original selectpicker, the data will be passed down to the cloned selectpicker.

**Comment by rublevma** [comment]
Please help, same issue. Made everything but error appear:
`Uncaught TypeError: Cannot read property 'ajaxOptions' of undefined`

**Comment by markcarver** [comment]
Please read jQuery's documentation on how [$.fn.clone](https://api.jquery.com/clone/) works.

**Comment by rublevma** [comment]
Maybe i need replace ajaxOptions something else?
