### ISSUE TITLE
Look into adding infinite scroll

### ISSUE THREAD

**Issue by truckingsim** [truckingsim/Ajax-Bootstrap-Select#32]
This will more than likely have to go into another file that would be included on the page rather than in the core (or we release a version with infinite scroll and version without), but don't want to bloat the core bigger than it needs to be.

**Comment by truckingsim** [comment]
So we can listen to scroll with the following listener:

`this.$element.data().selectpicker.$menu.find('.inner').on('scroll', function(e){`

@markcarver do you know of a better way to access  that.  The good news is that the $menu and .inner items are never rebuilt.  Even on close and open, rendering, etc.  Once instantiated they are always there.  So we will ever only need to add one listener and shouldn't need to reattach it again.

Since we can listen to scroll the limitation now is how do we want to do paging.  We can easily tell when they reach the bottom (or a threshold) but do we keep firing page requests as they reach the bottom? Do we add a way to logically know they've reached the bottom (off of request return value)?

Etc... Also this is going to require either changing quite a few places to work with scrolling (i.e. we currently wipe out the results always, we would need to add a way to append them).  Or do we want to make this a separate plugin that overrides the areas it needs to override?

**Comment by markcarver** [comment]
I don't think this is going to happen for reasons mentioned in related issue.

**Comment by AlokArora** [comment]
Waiting for this to happen, I'm using it for self created tool which lists approx 90K products with thumbnails on each option.
Now imagine if a search with 4 characters returns 10K matching records, it simply blocks the browser noticeably for a few seconds.

Somehow I have limited that to be 4 chars, though not supported by beloved ajax-bootstrap-select in it's original state, would you guys mind if raise I a pull request for this one?
