### ISSUE TITLE
[Proposal] Use dataSource to store object items and events

### ISSUE THREAD

**Issue by gperdomor** [truckingsim/Ajax-Bootstrap-Select#33]
Hi, this plugin is awesome, but i think would be better if offers the possibility to have a dataSource or something like that, why?, keep reading :D...

I'm working on a project using this plugin, but in some cases, i need execute some function on select event, the problem is when that function needs a field of the object represented in the options list, for example, in my project, the ajax request return a client list, where the client's id is the 'value' and the client's name is the 'text' shown on the options list of the plugin, i need execute a function for validate or show something using/depending of another field of the client, like status or email (any field can be used), but i can't access to these fields.

My proposal is add a 'item' parameter on the json returned in the ajax request, and that field contains the complete object (or extra fields if the object have too many fields and not all of them are needed on the client-side) represented in the ajax request, and add a method like getItem(), which return the item selected instead of the value as the "val()" method does.

Twitter Typeahead plugin have a event ('typeahead:selected') which is fired when the user select an item, and the function of this event has two parameters, the event himself and the item with the object. Would be nice have something like that here....

this is my json proposal:

    [
        {
            item: object
            value: 'string', 
            text: 'string',
            class: 'string',
            disable: false, 
            divider: true,
            data: {
                divider: true,
                subtext: 'string',
                icon: 'class-name', // Icon class name ex: icon-glass
                content: '<div class="custom-class">my value label</div>',
            }
        }
        ....
    ]

Would be nice too, have events like onOpen, onClose, onSelect, beforeRequest, afterRequest, etc :+1:

**Comment by truckingsim** [comment]
Bootstrap select has added events I don't think there's anything else to add here closing this.
