### ISSUE TITLE
On change problem

### ISSUE THREAD

**Issue by fredw** [truckingsim/Ajax-Bootstrap-Select#35]
I'm with a problem in the onchange trigger of select.
While I'm doing research via ajax the on change trigger of the select is called multiple times.
The "on change" should be done differently?
I'm placing down the script I made for my test environment to simulate the error:

    <select name="country" class="form-control" required="required" data-live-search="true"></select>

    <script>

        $(document).ready(function() {

            $('select[name=country]').selectpicker().ajaxSelectPicker({
                cache: false,
                preserveSelected: false,
                ajaxOptions: {
                    url: 'http://beta.json-generator.com/api/json/get/HPmtU2d',
                    type: 'POST',
                    dataType: 'json',
                    data: function () {

                        var params = {
                            q: '{{{q}}}'
                        };

                        return params;
                    }
                }
            }).on('change', function() {
                console.log('Changed!');
            });
        });

    </script>

**Comment by truckingsim** [comment]
@fredw sorry it took so long but the 1.3.1 branch I think will fix your problem.  If it doesn't let me know and I'll re-open this and try to come up with something better.

**Comment by adrm** [comment]
@truckingsim I can reproduce this bug on 1.8.1. `onchange` event is firing every time the ajax search completes, even before selecting anything.

**Comment by pudjamansyurin** [comment]
same problem with @adrm, no solution yet
