### ISSUE TITLE
Pass content from another Select

### ISSUE THREAD

**Issue by davidlettice** [truckingsim/Ajax-Bootstrap-Select#36]
Hey,

Following my post a few days ago (https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/34), I've expanded my form a bit more now, so it now includes the venue. As a rule of thumb, this should be the venue of the home team, but with the option to change if necessary (for example, a cup final).

So I've set a change request set to the home team that adds the relevant venue in to the venue select box. For the most part, this is working, and it does actually add the option value in correctly. It just doesn't visually display the change. I've tried instantiating ajaxSelectPicker like you suggested, and refreshing/re-rendering the selectpicker, but I'm drawing blanks.

```javascript
$('#home_team1').change(add_venue);

function add_venue()
  {
    var option = $(this).find(':selected').val(),
    dataString = "option="+option;
    if(option != '')
    {
        $.ajax({
            type     : 'GET',
            url      : 'ajax.php',
            data     : dataString,
            dataType : 'JSON',
            cache: false,
            success  : function(data) {            
                var output = '';

                $.each(data.data, function(i,s){
                    var newOption = s;

                    output += '<option value="' + newOption["team_home_venue"] + '">' + newOption["venue_name"] + '</option>';
                });

                $('#venue1').empty().append(output);
            },
            error: function(){
                console.log("Ajax failed");
            }
        }); 
    }
    $('#venue1').selectpicker('refresh').selectpicker('render').ajaxSelectPicker();
}
```

Is there any way to completely re-render the select based on what would be perceived to be it's existing options, or am I simply asking too much from the extension? Alternatively, there may be a better way of doing this, although I've been through both sets of documentation and I'm struggling to find a way

**Comment by truckingsim** [comment]
Closing this since he never responded.
