### ISSUE TITLE
Make this select required

### ISSUE THREAD

**Issue by nevits8as** [truckingsim/Ajax-Bootstrap-Select#38]
I need to make required this field in a form via bootstrap like formvalidation do

**Comment by truckingsim** [comment]
I'm not sure what exactly your looking for but this isn't something this plugin or bootstrap-select does.  You can put validation on the original select (the one you use to call ajaxSelectPicker()).  Everything we do is on that original select and then we just refresh the bootstrap-select.

So not sure what you are looking for here?

**Comment by markcarver** [comment]
Agreed, this project does not handle input element requirements nor any sort of validation. It's sole purpose is to provide the AJAX capabilities for the [bootstrap-select](https://github.com/silviomoreto/bootstrap-select) plugin.

**Comment by nevits8as** [comment]
im looking for make one ajaxselectpicker required (mandatory) with formvalidation
