### ISSUE TITLE
Keyboards action not working

### ISSUE THREAD

**Issue by enyosolutions** [truckingsim/Ajax-Bootstrap-Select#40]
Hello, 
Thanks for writing this plugin.
I'm having some issues with the keyboard behaviors. For example :

>> The arrows up and down keys do not scan through the content, hence blocking keyboard only navigation

>> The enter button does not select a value. 

Thoses are currently standaard behaviors in the bootstrap select plugin. Is there a way to restore this functions ?

thanks in advance.

**Comment by truckingsim** [comment]
Can you see if you can reproduce this in a JSFiddle?  I have a starting fiddle [here](http://jsfiddle.net/jefffan24/okbnumdc/) which does work.  Can you see if you can change what you need to change to get it to happen.

**Comment by victorwpbastos** [comment]
I'm having this problem too in Bootstrap Select v1.6.4. Version 1.6.3 is fine!

**Comment by truckingsim** [comment]
This looks like a bug with Bootstrap Select.  If you strip it down to the most basic like [this fiddle](http://jsfiddle.net/jefffan24/g6jntgxL/) then you'll see that the problems from the original message are happening.

This needs to be fixed in bootstrap-select nothing we can do about it.
