### ISSUE TITLE
Using ajax with preselected option

### ISSUE THREAD

**Issue by gregora** [truckingsim/Ajax-Bootstrap-Select#45]
Hi,

I'm trying to use the ajax select with an update form, like the example in this fiddle: http://jsfiddle.net/okbnumdc/10/. Basically, before the first ajax is sent, I already want to have one option selected.

What I did is I took a working example (http://jsfiddle.net/okbnumdc/9/) and just added an existing option to the select list with an attribute "selected". It is shown as selected at first, but when I try to choose a different option, the select message turns to "Select and Begin Typing". Is there a bug with preselecting an option? 

Best regards,
Gregor

**Comment by truckingsim** [comment]
This issue: https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/41 applies to single selects as well.  I still haven't figured out why the heck its not working on pre selected options.  If you figure out anything when working through this please let me know.  Right now I could take any information.

Sorry its not working for you.

**Comment by sharmi89** [comment]
Hi guys,
I had also the same issue that i have some options before load ajax bootstrap select to a element.
But i resolve by using 

       $('your element ID').trigger('change');
after you add the ajax bootstrap select.

in your example http://jsfiddle.net/okbnumdc/10/ add this line in the end of js.
$('select').trigger('change');

It works fine for me but couldn't keep more then one options. If any one can resolve it let me know please.

**Comment by truckingsim** [comment]
@sharmi89 it couldn't keep more than one option in the example at least because it wasn't a multi select.

See: https://jsfiddle.net/okbnumdc/14/ for an example with multi select working with your patch for at least temporarily resolving this.

**Comment by gregora** [comment]
Thanks @sharmi89! Your solution works like a treat. 

At least in the fiddle, I still have to figure out why it fails in my project, but that is another story :)

**Comment by truckingsim** [comment]
#76 should fix this.  If its still an issue open a new issue.
