### ISSUE TITLE
When options are rebuilt from cache, the change event isn't triggered

### ISSUE THREAD

**Issue by pauloprea** [truckingsim/Ajax-Bootstrap-Select#50]
Scenario to reproduce:
- search initial query (no cache)
- list is populated, change is fired
- select item, change is fired (here you can actually link to other logic to check for the selected value)
- search for second query (no cache) - same behavior
- search a third time - options are destroyed, selected item is None - change event not fired
- use first query (from cache)
- list is populated, change is not fired
- don't select anything.

At this stage, the state of the system is:
- option list is based on first query, built from cache
- no item is selected
- the last selected value you can get is from a previous step, making it impossible to have consistent logic in binding behaviors to other DOM elements.

In practice, you might want to have dependable selects and this prevents achieving that. Typically, it should work in such manner that whenever the first select changes value, the second select is enabled and it's query is enhanced so you can filter on related options.

**Comment by truckingsim** [comment]
@pauloprea thanks for the detailed use case.  That will help.  It would also help if you could rebuild that behavior (even if it just console.logs the change event) with [this JSFiddle](https://jsfiddle.net/jefffan24/okbnumdc/). It has a working version of bootstrap-select and ajax-bootstrap-select and filtering.

I don't know when I'm going to have time to look into this but I really want to get 2.0 out and that includes fixing some bugs.  So any info you can get me before the weekend is greatly appreciated.

**Comment by pauloprea** [comment]
Thank for the fiddle. Helped tracking it down and from what I can tell it's an issue in bootstrap-select itself, at least version 1.7.2. which I was using. Works as expected with 1.6.3. I think we can close this, unless you want to be looking into compatibility issues.

**Comment by truckingsim** [comment]
I am going to close it for now.  When we release V2, if the problem still persists (we are going to rely on a minimum version of 1.7.2) if you could make a new issue that would be great.

**Comment by pauloprea** [comment]
Deal

**Comment by pauloprea** [comment]
After more fiddling, I can confirm that this is related to #22, especially with selectedTextFormat = 'static' being set in setTitle(). Removing it fixes the behavior with bootstrap-select=1.7.2.

**Comment by truckingsim** [comment]
Interesting thanks for letting me know.
