### ISSUE TITLE
Bug with selection on ie10

### ISSUE THREAD

**Issue by EdouardTack** [truckingsim/Ajax-Bootstrap-Select#51]
Hello,
I found a bug with your plugin and ie10. Yon can just try it with the exemple in the plugin directory (/example/php/).
With the multiple selectpicker, try to write anything, then select all, and try to deselect all.
We can't deselect options and they are all selected or not every other time.

Do you have any idea to fix it ?

thanks

**Comment by adrm** [comment]
I was able to replicate this using version 1.6.3 of bootstrap-select. Updating that library to 1.6.5+ fixed it for me.

**Comment by truckingsim** [comment]
Considering @EdouardTack never came back on this one and based on @adrm's comment I'm going to close this as a bug with bootstrap-select rather than us.
