### ISSUE TITLE
Get values from another input or select when it change

### ISSUE THREAD

**Issue by ptykamikaze** [truckingsim/Ajax-Bootstrap-Select#53]
Hi.. first of all, thanks for this plugin because it is great and it helps me with something I am creating...

I have the following problem:

1. Lets say that this is the ajax part of the picker options for a SELECT_2:

    ajax: {
        url: app_url + '/load_values',
        type: 'POST',
        dataType: 'json',
        // Use "{{{q}}}" as a placeholder and Ajax Bootstrap Select will
        // automatically replace it with the value of the search query.
        data: {
            q: '{{{q}}}'
			,'_token': 	$('input[name="_token"]').val()
			,'id': 		$('input[name="form_id"]').val()
			,'version': $('input[name="version"]').val()
			,'main_id': $('input[name="main_id"]').val()
			,'parent': 	$('select#SELECT_1').val()
			,'field': 	''
        }
    }

2. I call the plugin and it works as it is suppose to work: $(this).selectpicker({liveSearch: true}).ajaxSelectPicker(picker_options);

3. The problem I'm having is that the plugin is getting the first value of $('select#SELECT_1').val() when it is called. I want the plugin to get the current value when it is called. Problem is that value is static and I need to get dynamically the values of $('select#SELECT_1').val().. how can I do that? is it possible?

**Comment by truckingsim** [comment]
@ptykamikaze I'm not sure I follow.  Can you see if you can make a reproducible use case with this fiddle: [fiddle, click here](https://jsfiddle.net/jefffan24/okbnumdc/).

**Comment by ptykamikaze** [comment]
Here is the fiddle link:

https://jsfiddle.net/L8r0dtq7/  

The list of the second select, depends on the value selected in the first select... it is like in the server-side query will be a "WHERE" clause for filtering the result with a condition // WHERE dummy_column = "[SELECT1-VALUE]"

**Comment by truckingsim** [comment]
Try this: [fiddle](https://jsfiddle.net/jefffan24/j79yruqz/)

Basically when I built this I knew it was possibility that people may want to do what you asked so I made it possible to pass a function to `data` in the ajax options.  That function will get run every time we do a server request.  So it should do what you are looking for.

Let me know if that works for you or not.

**Comment by ptykamikaze** [comment]
It works! thanks a lot!

**Comment by cristiammercado** [comment]
I think this issue should be described in the documentation, because it happened to me and I'm sure  other people too!
