### ISSUE TITLE
TYPO mistake

### ISSUE THREAD

**Issue by ruros** [truckingsim/Ajax-Bootstrap-Select#58]
Rename 'disable' to 'disabled' attribute in the readme in #json-results and #usage-example paragraphs.

```javascript
{
    ....
    disable: false,     // {Boolean} true|false
    ....
}
```

**Comment by markcarver** [comment]
Fixed by https://github.com/truckingsim/Ajax-Bootstrap-Select/commit/45739e09e00845f0c08219ffd2c65ca1bcedd217
