### ISSUE TITLE
Allow AJAX URL to be provided using a function

### ISSUE THREAD

**Issue by ashanmadushka** [truckingsim/Ajax-Bootstrap-Select#59]
hello,

is there any way to change the ajax selectpicker url according to change of any thing?
do any one have idea of doing it?

thanks.

**Comment by bvvnbsp** [comment]
Hi, try this `$('#el').data('AjaxBootstrapSelect').options.ajax.url = '/some-new-url'`

**Comment by truckingsim** [comment]
While what bvvnbsp said would work we should probably just make url be able to be a function like data can.  It wouldn't be hard to do, adding that as something we can do for 2.0.0.

**Comment by viethien** [comment]
@ghost thank you, it worked

**Comment by markhalliwell** [comment]
Actually, this has already been done lol

See #154
