### ISSUE TITLE
Selected item disappears while searching

### ISSUE THREAD

**Issue by christophe** [truckingsim/Ajax-Bootstrap-Select#64]
Hi again,

When an item is currently selected, an the user is starting a new search, the currently selected item disappears, firing any triggers bound to the 'change' event when in effect, no change has happened yet (i.e. no new selection has occurred).
Also, when the user does not select a new item, but cancels out of the dropdown, the select loses its selected item.

While this behaviour is understandable, as the selected item is not a match for the new filter, I think it would be nice to have an option to keep the selected item in the dropdown as long as no other is actively selected.

Cheers,

Christophe

**Comment by christophe** [comment]
I found the preserveSelected option which, by its description, should solve this issue. However, setting it to true, does not seem to have any effect.

**Comment by truckingsim** [comment]
@christophe can you see if this is fixed in `v1.3.6`

**Comment by truckingsim** [comment]
If it is still a problem after trying the latest release please open up a new issue.
