### ISSUE TITLE
Set first value (Previously selected value)

### ISSUE THREAD

**Issue by morozp** [truckingsim/Ajax-Bootstrap-Select#66]
Excuse  me, but how I can set first selected value to  selectpicker when page loading first. 
If I create simple html  <select> <options 'selected'> ...</select>
Selected value applyed, but when I start search  - selected value cleared , and when I select from search result new selected value not dIsplayed.( IE 11 , chrome)

**Comment by BrnoPCmaniak** [comment]
Take a look at #45 might be a solution.

**Comment by truckingsim** [comment]
@morozp this should be fixed in #76
