### ISSUE TITLE
Set default data programatically

### ISSUE THREAD

**Issue by bvisonl** [truckingsim/Ajax-Bootstrap-Select#67]
I cannot use selectpicker('val', 'data') or anything like that to set the default selected item. Lets say that for example I am editing a record, how do I set the data that the record previously had? I am talking about single select. 

I have tried using the selectpicker.val('data')  or selectpicker('val', 'data') and also called 'render' or 'refresh' after and nothing works.

I also tried to programatically trigger the search to search for the previously selected item but programatically I don't know how to.. I tried forcing a value into the search input in .bs-searchbox but this didn't work either.. kind of need this asap! thanks in advance.

**Comment by BrnoPCmaniak** [comment]
I'm using this for clear button might help.

    $(document).on('click', '#ajax-student-clear', function(){
             $("#ajax-select-students").val('').trigger('change');
         })

**Comment by PoetikDragon** [comment]
I am also interested in this answer, its the final piece of my form I need to resolve.

**Comment by bvisonl** [comment]
@PoetikDragon here is what I ended up using I did a lot of digging in the inspect element to figure this out:

    // Terrible hack to set the default data.
    // Todo: NEED TO CHANGE THIS! UNCLEAN
    var $productAssociationInput = $(".product-associated");
    var $currentProductAssociated = $productAssociationInput.val();
    if($currentProductAssociated != "") {
        $(".product_associated_div").find(".bootstrap-select").find("button").remove();
        $(".product_associated_div").find(".bootstrap-select").prepend('<button type="button" class="btn dropdown-toggle selectpicker btn-default" data-toggle="dropdown" data-id="product_associated" title="'+$currentProductAssociated+'"><span class="filter-option pull-left">'+$currentProductAssociated+'</span>&nbsp;<span class="caret"></span></button>');
    }

in "currentProductAssociated" you put the default data that you want in the select, the .product_associated_div is just a div around the bootstrap select so I can navigate through the elements.

Let me know if this works for you

**Comment by nicebag** [comment]
Might be cleaner solution:

```
$("#oib").empty();
$("#oib").append("<option value='test'>Test</option>");
$("#oib").selectpicker("refresh");
```

**Comment by ganaited** [comment]
Ugly as f*uck

var $abs = $('select').selectpicker(options).ajaxSelectPicker(options);
var selected = { value: value, title: title };

$abs.val(selected.value).trigger('change').selectpicker('refresh');
$abs.data('AjaxBootstrapSelect').list.setTitle(selected.title);
$abs..data('AjaxBootstrapSelect').list.refresh();

**Comment by dduleep** [comment]
I have the same issue and looking for a solution around documentation and StackOverflow, but I'm not lucky enough to get solution except for this close ISSUE. 

I have tried @ganaited solution but I'm not clear about the **options**  variable of his solution. kindly apologize for my JS knowledge
