### ISSUE TITLE
Is it possible to populate data without search?

### ISSUE THREAD

**Issue by kutec** [truckingsim/Ajax-Bootstrap-Select#69]
I am using bootstrap-select and I don't need searchbox to be fetched data. Data should be loaded on document.ready() and should work in the same manner like bootstrap-select.

I checked your code if we can disable search and get the data on load. But I couldn't find any.

Can you please let me know if it's possible somehow?

**Sample Script**:

```
var options = {
                ajax          : {
                    url     : 'https://crossorigin.me/https://teckstack.com/wp-json/wp/v2/posts',
                    type    : 'GET'
                },
                log           : 3,
                preprocessData: function (data) {
                    var i, l = data.length, array = [];
                    if (l) {
                        for (i = 0; i < l; i++) {
                            array.push($.extend(true, data[i], {
                                text : data[i].id,
                                value: data[i].title.rendered,
                                data : {
                                    subtext: data[i].title.rendered
                                }
                            }));
                        }
                    }
                    // You must always return a valid array when processing data. The
                    // data argument passed is a clone and cannot be modified directly.
                    //return array;
                }
            };
            $('.selectpicker').selectpicker({
                liveSearch: false
            }).filter('.with-ajax').ajaxSelectPicker(options);
            $('select').trigger('change');
```

Thanks.

**Comment by kutec** [comment]
Hey, did you check this?

**Comment by truckingsim** [comment]
@kutec so you want to do like a single fetch once after page load correct?  If so you don't need ajax-bootstrap-select for that and it doesn't support it.

You can do this with just bootstrap-select by doing the ajax request when you need it, setting the `<option>` tags on the original select and then calling: `$('.selector').selectpicker('refresh')`.  If I understand what you are asking that should cover what you want to do.

If I'm not understanding what you are asking let me know.

**Comment by truckingsim** [comment]
I'm closing this, but going to leave it open to comment.  @kutec if you have any other issues go ahead and comment but giong to assume that comment above resolves your issue.

**Comment by kutec** [comment]
Hey @truckingsim thanks for responding. I tried with `$('.selector').selectpicker('refresh')` but it couldn't help. Could you please share a sample code or demo?

**Comment by truckingsim** [comment]
@kutec did you update the options in the select before calling refresh?
