### ISSUE TITLE
Problems first list item

### ISSUE THREAD

**Issue by wallysonn** [truckingsim/Ajax-Bootstrap-Select#70]
When I search the first item is selected by default, how to get around this?
<img class="img" src="http://i.imgur.com/oAq9F7t.png" alt="Image Preview" />

**Comment by wallysonn** [comment]
I solved the problem including the first record with the empty value

**Comment by vitorhorta** [comment]
I am having the same issue. Does anybody know another way to solve it? Adding an empty value doesn't seen to be the best choice
