### ISSUE TITLE
Select to allow free entry with an option

### ISSUE THREAD

**Issue by stan74fr** [truckingsim/Ajax-Bootstrap-Select#71]
Hi Adam,

thks for the plugin which I am enjoying and adding in one project. I am using it with the ajax-picker addition to improve performance. Would there be any ways to allow users to enter free text (their own text) if not fund in the list? Long term addition as an option would be great but a short term hack would be welcomed. Thks and hello from France.

Stan

**Comment by truckingsim** [comment]
@stan74fr been thinking about this and I don't think we will add it.  You could technically fork this and add special logic for if someone presses enter with no results it handles that logic.  But we won't be adding that to this if for no reason other than I don't have the time to maintain the current set of features let alone adding something like this.

**Comment by stan74fr** [comment]
Thks Adam for your reply. Even if I like it on some aspects, I am on hold in terms of using it in my projects due to this shortcoming. At this stage I have to mix it with some others. By the way, for anyone interested by rails 4 integration, I have made an example below. Will come back. 

https://github.com/stan74fr/Rails-4-form-with-Tags-Input
