### ISSUE TITLE
Please minify the css file

### ISSUE THREAD

**Issue by x09326** [truckingsim/Ajax-Bootstrap-Select#72]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

Could you minify the **ajax-bootstrap-select.css** in the **dist/css**.
Thank you for your help!

https://github.com/cdnjs/cdnjs/issues/7838#issuecomment-218640171

**Comment by truckingsim** [comment]
@x09326 css in minified now starting with v1.3.5 release/tag.
