### ISSUE TITLE
ajax data - custom definition on attribute

### ISSUE THREAD

**Issue by riwos** [truckingsim/Ajax-Bootstrap-Select#80]
Hi,

Let assume we have a definition control:

```
 $("#www").selectpicker().ajaxSelectPicker();

 <select id="www" class="form-control" type="select" style="display: none;"  data-style="btn-default" data-live-search="true" data-abs-ajax-url="/example.com/test/action?test1,test2" data-abs-ajax-type="get" data-abs-ajax-data="?????what I should put??????">
                                <option>Mustard</option>
                                <option>Ketchup</option>
                                <option>Relish</option>
                            </select>
```

I do not want something that: /example.com/test/GetAction?action=test1,test2**&q=Mustard**

What I should to do to get example request: **/example.com/test/GetAction?action=test1,test2,Mustard** ?? What I should put on attribute "data-abs-ajax-data" to get this result.. Any idea ??

**Comment by truckingsim** [comment]
It's been almost a year, if you still need help with this please open a new issue.
