### ISSUE TITLE
"No Results" when responseJSON formatted "correctly"

### ISSUE THREAD

**Issue by ApeWare** [truckingsim/Ajax-Bootstrap-Select#81]
I'm trying to implement Ajax-Bootstrap-Select and keep getting *No Results* though results are being returned. I have verified that I am returning JSON, [formatted like the docs suggest](#json). 

According to the [console](#console) the package **is** receiving the responseJSON yet is still returning *No results were returned.* I have also tried to return an array and use the `preprocessData` method to preprocess the request yielding the same results. I am obviously missing something and hope someone can point me in the right direction.

### HTML Code
```HTML
...
<div id="ps-naics" class="form-group">
    <label for="ps-field-naics"><small>NAICS Code</small></label>
        <select multiple
            id="ps-field-naics"
            class="selectpicker with-ajax show-tick"
            name="search['parameters']['naics'][]"
            data-size="6"
            data-live-search="true"
            data-actions-box="false"
            data-selected-text-format="count > 1"
            data-header="Select NAICS CODE(s)"
            data-abs-restore-on-error="false"
            data-abs-request-delay="5000"
            title=""
            size="1"
            data-width="100%"
            data-dropup-auto="true">
    </select>
</div>
...
```

### Javascript Code

```JAVASCRIPT
 var options = {
    ajax          : {
        url     : '/api/filterNaics',
        type    : 'POST',
        dataType: 'json',
        data    : {
            q: '{{{q}}}'
        }
    },
    locale        : {
        emptyTitle: 'Select and Begin Typing'
    },
    log           : 4
};
$('.selectpicker').selectpicker().filter('.with-ajax').ajaxSelectPicker(options);
$('#ps-field-naics').trigger('change');
```

### Returned JSON<a name="json"></a>
This is the response from `/api/filterNaics` where q=shirt
```JSON
[
    {
        "naicsCode" : "315223",
        "naicsTitle" : "Men's and Boys' Cut and Sew Shirt (except Work Shirt) Manufacturing",
        "class" : "",
        "disabled" : false
    },
    {
        "naicsCode" : "315291",
        "naicsTitle" : "Infants' Cut and Sew Apparel Manufacturing",
        "class" : "",
        "disabled" : false
    },
    {
        "naicsCode" : "315211",
        "naicsTitle" : "Men's and Boys' Cut and Sew Apparel Contractors",
        "class" : "",
        "disabled" : false
    },
    ...
]
```

### Console Output<a name="console"></a>
Notice the `responseJSON` and `responseText` appear to be formatted according to docs - *unless I am missing something*

![image](https://cloud.githubusercontent.com/assets/389759/17145257/83d4a4d2-5327-11e6-8c3d-1353af1aa6cf.png)

**Comment by truckingsim** [comment]
@ApeWare `value` is a required field in the json response for each object.  If you don't want value to the text for the option then you can also return a `text` property.

```json
[
    {
        "naicsCode" : "315223",
        "naicsTitle" : "Men's and Boys' Cut and Sew Shirt (except Work Shirt) Manufacturing",
        "value" : "315223",
        "text" : "Men's and Boys' Cut and Sew Shirt (except Work Shirt) Manufacturing",
        "class" : "",
        "disabled" : false
    },
    {
        "naicsCode" : "315291",
        "naicsTitle" : "Infants' Cut and Sew Apparel Manufacturing",
        "value" : "315291",
        "text" : "Infants' Cut and Sew Apparel Manufacturing",
        "class" : "",
        "disabled" : false
    },
    {
        "naicsCode" : "315211",
        "naicsTitle" : "Men's and Boys' Cut and Sew Apparel Contractors",
        "value" : "315211",
        "text" : "Men's and Boys' Cut and Sew Apparel Contractors",
        "class" : "",
        "disabled" : false
    },
    ...
]
```
I made some assumptions but that's what a correct response would look like.

You can also return the structure like you have now and use [preprocessData](https://github.com/truckingsim/Ajax-Bootstrap-Select#optionspreprocessdata) to manipulate the object returned from the server into the thing Ajax-Bootstrap-Select needs.  The [usage example](https://github.com/truckingsim/Ajax-Bootstrap-Select#usage-example) uses `preprocessData` if you need an example of how to use it.

Let me know if you have any other questions or if this doesn't work for you.

**Comment by ApeWare** [comment]
Thanks for the quick response! At one point I did have `naicsCode` named `value` - forgot why I changed it; changing it to `value` fixed the issue. 

Thanks again for the quick response and for this package! :-)

**Comment by truckingsim** [comment]
No problem, glad it was an easy fix!
