### ISSUE TITLE
data-size does not work

### ISSUE THREAD

**Issue by ir0ncurtain** [truckingsim/Ajax-Bootstrap-Select#82]
I have an issue while using the plugin. My problem is that when I am searching for items and there are big amount of results , vertical scrolls are not appearing. I have data-size set to 10 and it works only after I close and reopen the drop down list. Please help.

```
` 
$('#ddlLocation')
        .selectpicker({
        })
        .ajaxSelectPicker({
            ajax: {
                url: '@(Url.RouteUrl("Search"))',
                type: "POST",
                dataType: "json",
                data: function () {
                    var params = {
                        Filter: '{{{q}}}',
                        CountryName: 'USA'
                    };

                    return params;
                }
            },
            locale: {
                emptyTitle: 'Search for Location...'
            },
            preprocessData: function (data) {
                var i, l = data.length,
                    arr = [];
                if (l) {
                    for (i = 0; i < l; i++) {
                        if (data[i].Location.toLowerCase().indexOf(this.plugin.query) != -1 || data[i].Location.toLowerCase().indexOf(this.plugin.query) != -1) {
                            arr.push($.extend(true, data[i], {
                                text: data[i].Location,
                                value: data[i].ID,
                                disabled: false
                            }));
                        }
                    }
                }

                return arr;
            },

            preserveSelected: false,`
```

**Comment by truckingsim** [comment]
@ir0ncurtain can you see if you can replicate the bug by forking this fiddle: <https://jsfiddle.net/jefffan24/okbnumdc/>

**Comment by ir0ncurtain** [comment]
@truckingsim unfortunately I am not able to post my example to this page.

 I noticed in dev tools that when I am searching for items the list style is:
`style="min-height: 0px;"`
but when I close the drop-down list it changes to `style="max-height: 260px; overflow-y: auto;"`

**Comment by truckingsim** [comment]
@ir0ncurtain that jsfiddle hsa its own data set, just need you set the `data-` properties on the select and the correct properties in the JS and see if has the same problem.  If I can't see the problem its going to be hard to help you.

**Comment by ir0ncurtain** [comment]
@truckingsim I have one question. I set `window.alert('test')` just after ` ```
if (l) {
                    for (i = 0; i < l; i++) {
                        if (data[i].Location.toLowerCase().indexOf(this.plugin.query) != -1 || data[i].Location.toLowerCase().indexOf(this.plugin.query) != -1) {
                            arr.push($.extend(true, data[i], {
                                text: data[i].Location,
                                value: data[i].ID,
                                disabled: false
                            }));
                        }
                    }
                }
```
but it was never reached out. Do you know why? Maybe if I could set somewhere `$('#ddlLocation').selectpicker('refresh');` it would resolve my issue?

**Comment by truckingsim** [comment]
@ir0ncurtain `preprocessData` only runs when a search is done.   You have to type in the textbox in the selectpicker to trigger that function.  It doesn't run on load.

**Comment by ir0ncurtain** [comment]
This is what I did and it worked for me:

`preprocessData: function (data) {
            var results = [];
            $.each(data, function (index, account) {
                results.push(
                    {
                        'value': account.ID,
                        'text': account.Location,
                        'disabled': false
                    }

                );
            })

            $('div.dropdown-menu.open').css({ 'max-height':'314px', 'overflow':'hidden'});
            $('ul.dropdown-menu.inner').css({ 'max-height': '260px', 'overflow-y': 'auto' });

            return results;


        },`

**Comment by pppdns** [comment]
The issue is here in `bootstrap-select`:
https://github.com/silviomoreto/bootstrap-select/blob/v1.12.2/js/bootstrap-select.js#L1012

```
} else if (this.options.size && this.options.size != 'auto' && this.$lis.not(notDisabled).length > this.options.size) {
```

with this part of the code: `this.$lis.not(notDisabled).length > this.options.size`

If populating the options AFTER the initialization (e.g. using AJAX) the dropdown's max height won't be set and it will have no max height because `this.$lis.not(notDisabled).length > this.options.size` at that time as `this.options.size` will be 0

**Comment by marcusfritze** [comment]
if fixed it by adding a setTimeout:

```
preprocessData: function (data) {

var arrayData = [];

[...]

setTimeout(function () {
$('#idOfSelect').selectpicker('setSize');
}, 1);

return array;
}
```
