### ISSUE TITLE
Dynamic parameters to request using ajax (from input text html)

### ISSUE THREAD

**Issue by khnoize** [truckingsim/Ajax-Bootstrap-Select#83]
I'm trying to make ajax parameters on my html request to become dinamic, below is my code:  

```
var options = {
    ajax          : {
        url     : 'ajax.php',
        type    : 'POST',
        dataType: 'json',
        // Use "{{{q}}}" as a placeholder and Ajax Bootstrap Select will
        // automatically replace it with the value of the search query.
        data    : {
            q: '{{{q}}}',
            nama:$("#contoh").val()//this is an input text HTML
        }
    },
    locale        : {
        emptyTitle: 'Select and Begin Typing'
    },

    preprocessData: function (data) {
        var i, l = data.length, array = [];
        if (l) {
            for (i = 0; i < l; i++) {
                array.push($.extend(true, data[i], {
                    text : data[i].Name,
                    value: data[i].Email,
                    data : {
                        subtext: data[i].Email
                    }
                }));
            }
        }
        // You must always return a valid array when processing data. The
        // data argument passed is a clone and cannot be modified directly.
        return array;
    }
};

$('.selectpicker').selectpicker().filter('.with-ajax').ajaxSelectPicker(options);
$('select').trigger('change');
```

And the result is, the "nama" parameter isn't changed even though I already changed the text input by id "contoh". How's the solution"? Thank you.

**Comment by truckingsim** [comment]
@khnoize try this:

```js
var options = {
    ajax          : {
        url     : 'ajax.php',
        type    : 'POST',
        dataType: 'json',
        // Use "{{{q}}}" as a placeholder and Ajax Bootstrap Select will
        // automatically replace it with the value of the search query.
        data    : function() {
            return {
               q: '{{{q}}}',
               nama:$("#contoh").val()//this is an input text HTML
            };
        }
    },
    locale        : {
        emptyTitle: 'Select and Begin Typing'
    },

    preprocessData: function (data) {
        var i, l = data.length, array = [];
        if (l) {
            for (i = 0; i < l; i++) {
                array.push($.extend(true, data[i], {
                    text : data[i].Name,
                    value: data[i].Email,
                    data : {
                        subtext: data[i].Email
                    }
                }));
            }
        }
        // You must always return a valid array when processing data. The
        // data argument passed is a clone and cannot be modified directly.
        return array;
    }
};

$('.selectpicker').selectpicker().filter('.with-ajax').ajaxSelectPicker(options);
$('select').trigger('change');
```

The data property can be a function that is then run on each new request.  That should make the nama dynamic.

**Comment by truckingsim** [comment]
Closing since no response for 9 months.

**Comment by reloxx13** [comment]
Heya,
i know this issue is old but i got the same issue and found this by googling :p

Your suggestest solution does not work.

it looks like the .data("AjaxBootstrapSelect") (where the options are saved) on the selectpicker Element does not get updated.

Even not if i destroy the selectpicker and i did not find a destroy ajaxselectpicker in your code.
There is only a list destroy.

So my solution was to just re-set the desired value in the  .data("AjaxBootstrapSelect").

Use-case: i have 2 selectboxes, one for customers, one for contacts of the choosen customer.
Now on changing the customer, only contacts from this customer should appear in the contact selectbox.

So this is my solution:

```
$(".selectpicker#customer_id").on("changed.bs.select", function (e, clickedIndex, isSelected, previousValue){
   $(".selectpicker#contact_id").data("AjaxBootstrapSelect").options.ajax.data.customer_id = $(e.currentTarget).val();
});
```

**Comment by ribubrar** [comment]
I am trying to load the dropdown options using ajax. My options are getting displayed but I am unable to do the live search. Could you please check if my code misses any key parameters that hinder live search.

When I change the class from selectpicker to bootstrap-select, it works as expected.

`

<body>

    <div>

        <select class="selectpicker" multiple data-selected-text-format="count" data-actions-box="true" data-live-search="true" data-show-tick="false" data-live-search-style="contains">
        </select>

    </div>

    <script>

        var options = {

            ajax: {

            url: '/Search/Typeahead',

            type: 'POST',

            dataType: 'json',

            data: function () {
                var params = {
                    q: '{{{q}}}'
                };

                return params;
            }
        },

        locale: {
                emptyTitle: 'Select and Begin Typing'
        },

        preprocessData: function (data) {
            var i, l = data.length, array = [];
            if (l) {
                for (i = 0; i < l; i++) {
                    var curr = data[i];

                    array.push({
                        'value': curr.value,
                        'text': curr.text,
                        'disabled': curr.disabled,
                        'selected': curr.selected,
                    });
                }
            }
            return array;
        },
        preserveSelected: false
    };
    $('select.selectpicker').selectpicker({liveSearch: true }).ajaxSelectPicker(options);
        
    //The dropdown options are not displayed at all if I use **.filter('.with-ajax')** as below:
    //$('select.selectpicker').selectpicker({liveSearch: true }).filter('.with-ajax').ajaxSelectPicker(options);
        
    //Also tried using <select class="selectpicker **with-ajax** " but it doesn't work for me either

        $('select.selectpicker').trigger('change');
    </script>
</body>`
