### ISSUE TITLE
Dependent select

### ISSUE THREAD

**Issue by adaniello** [truckingsim/Ajax-Bootstrap-Select#84]
Hi,
i'ld connect two ajax-bootstrap-select: on change first select, a param (via abs-ajax-data data attribute) for the second should change ajax request, but not works.

This is my code:

```
$(document).on('change', '#projects_id', function(){
    $('#milestones_id').data('abs-ajax-data-conditions', 'projects_id=' + $('#projects_id').val()).selectpicker('refresh');
});
```
By console, i noted that data attribute for select#projects_id changes its value, but ajax call send always the initial value for "conditions".

Any suggestions? Thanks

**Comment by truckingsim** [comment]
@adaniello assuming you are trying to change the data sent to the server dynamically you can't do this through data attributes.  Ajax-Bootstrap-Select only looks at the data attributes once and that's on init.  You can do this with the data object you pass to `ajaxSelectPicker`:

```js
$('#milestones_id')
    .selectpicker({
        liveSearch: true
    })
    .ajaxSelectPicker({
        ajax: {
            url: '/server/path/to/ajax/results',
            data: function () {
                var params = {
                    q: '{{{q}}}'
                };
                params.project_id = $('#projects_id').val();

                return params;
            }
        }
    });
```

This will change the project_id sent dynamically.  The data function will be called with every ajax request.  No need for a change listener.  Let me know if this doesn't work for you, or if you have any other questions.

**Comment by adaniello** [comment]
Many thanks!
