### ISSUE TITLE
Displaying optgroup while live searching

### ISSUE THREAD

**Issue by avinashn-rapidd** [truckingsim/Ajax-Bootstrap-Select#86]
I'd like to have a version of live search that shows an optgroup and all its children if the search term matches the optgroup.

This would make working with large data sets that have parent -> child relationships a lot easier. It both shows the context that the optgroup provides, and allows users to filter by it.

For example, a selectpicker with optgroups:

Math
- Intro
- Algebra
- Calculus
- Number Theory

Science
- Intro
- Geology
- Physics
- Explosions Lab
  Then I search for Math and the following is shown:

Math
- Intro
- Algebra
- Calculus
- Number Theory
  Then I search for Intro and the following is shown:

Math
- Intro

Science
- Intro
  Then I search for Explosions Lab and the following is shown:

Science
- Explosions Lab

**Comment by rino7** [comment]
Hi, is any update about this feature? I'm interesting on it, too.

**Comment by pimduijst** [comment]
Plus 1!

**Comment by markcarver** [comment]
Dup of #31
