### ISSUE TITLE
Lag in search box during ajax live search when the number of options are more than 1000.

### ISSUE THREAD

**Issue by KshitizAgarwal21** [truckingsim/Ajax-Bootstrap-Select#87]
There is appreciable lag in the livesearch box of bootstrap select plugin when the options to be searched are very large for eg the no of cities in india.
please resolve this issue anyhow..pls.pls.pls

**Comment by markcarver** [comment]
This project does not and cannot control network latency. Any perceived lag from the server must be dealt with on the server itself. There are many techniques that exist to help mitigate this problem, however that is out of scope for this project. It is up to you to deal with it.
