### ISSUE TITLE
How to manually select items after page loaded?

### ISSUE THREAD

**Issue by archeg** [truckingsim/Ajax-Bootstrap-Select#89]
I'm using Ajax-Bootstrap-Select in a form that should be filled with data when page is loaded. How do I manually select items? My selectpicker is multiple-selection.

I've tried both:
```
var selectedElements = ["20958", "359", "327"] // These are item.value, they exist at the server
element.val(selectedElements);
element.selectpicker('render');
```
And
```
element.selectpicker('val', selectedElements);
```

Nothing happens. I assume this is because ajax-bootstrap-select didn't perform an ajax request yet, so there are no items. If I click on a select, execute some request against the server, this code start to work.

Is there any way how can I force to make ajax-bootstrap-select perform an ajax request, so I could fill the selected items in?

P.S.
My select definition is next:
```
<select id="@Html.IdForModel()" name="@Html.NameForModel()" class="selectpicker form-control" data-live-search="true" multiple></select>
...
 element.selectpicker().ajaxSelectPicker({
                     ajax: {
                         url: '@url',
                         type: 'GET'
                     },
                     preprocessData: function(data) {
                         var result = [];
                         for (var i = 0; i < data.length; i++) {
                             result.push({
                                 value: data[i].ProjectNo,
                                 text: data[i].Name,
                                 data: {
                                     content: "<div class='row'><div class='col-md-8'><b>" +
                                         data[i].ProjectNo +
                                         "</b></div><div class='col-md-8'>" +
                                         data[i].Name +
                                         "</div></div>"
                                 }
                             });
                         }
                         return result;
                     }
             });
```
I'm using bootstrap-select v1.11.2, bootstrap v3.3.7, jquery v3.1.0

**Comment by archeg** [comment]
I just realized that I can just generate a `select` with selected `options` inside:
 ```
<select id="@Html.IdForModel()" name="@Html.NameForModel()" class="selectpicker form-control" data-live-search="true" multiple>
        <option value="20958" data-content="<div class='row'><div class='col-md-8'><b>20958</b></div><div class='col-md-8'>Name1</div></div>">20958</option>
        <option value="359" data-content="<div class='row'><div class='col-md-8'><b>359</b></div><div class='col-md-8'>Name2</div></div>">359</option>
        <option value="327" data-content="<div class='row'><div class='col-md-8'><b>327</b></div><div class='col-md-8'>Name3</div></div>">327</option>
    </select>
```
 This seems to work and is OK way to do this for me, but I just wanted to check out whether this is the most simple way to do this. It would be more elegant if I didn't have to generate `option` elements by myself

**Comment by truckingsim** [comment]
@archeg as you saw setting with .val and `selectpicker('val', values)` doesn't work because the options aren't there.  There is no way right now to trigger an ajax request with Ajax-Bootstrap-Select.  I don't think this is something we will add either, this is something I would expect the backend to fill in not Ajax-Bootstrap-Select to handle.  If you can give me a good reason that feature should exist I might consider it but as of right now I don't consider that in the scope of the project.

**Comment by archeg** [comment]
@truckingsim That's fine. I just wanted to hear your opinion. If you say the best way is to fill it from the server-side, then let it be that. Thanks for the answer.
