### ISSUE TITLE
Deselecting doesn't work after adding the options to <select> on page load

### ISSUE THREAD

**Issue by andrius-senulis** [truckingsim/Ajax-Bootstrap-Select#90]
Hi all,

I am experiencing a wrong behavior. On page load I add the options to the `<select>` element as selected options:

``` html
<select id="filter_company" class="selectpicker" multiple title="..." data-live-search="true">
    <option value='company1' selected>Company 1</option>
    <option value='company2' selected>Company 2</option>
    <option value='company3' selected>Company 3</option>
</select>
```

In JS I initialize the `ajaxSelectPicker` as required with all necessary options use the trigger:

``` js
$('#filter_company').trigger('change');
```

However, deselecting doesn't work until I write a keyword in the search. Instead, on deselecting the items change positions but stay selected.

Does anyone else experience that and how could we solve this?

Cheers,
Andrius

**Comment by andrius-senulis** [comment]
I found out that deselecting only works if the options are selected by JS on page load instead of marking them as `selected` when rendering HTML:

```js
$('#filter_company').val(selected_companies).trigger('change').selectpicker('refresh');
```

However, it's still not ideal since the deselected options are not moved out from the "Currently Selected" `optgroup`, but that I can live with. Also, on deselecting the options are sorted depending on option "preserveSelectedPosition" (before/after) and it can be a little confusing for the user. If the deselected options were moved out from the "Currently Selected" `optgroup`, it wouldn't be confusing.

If anyone knows how to make it work correctly, please let me know.

**Comment by schmoove** [comment]
I've found that (on a Mac anyway) holding Command and clicking the item will remove it.

I can't find where in the source this is invoked though - the "meta" key (key code 91) is actually in the Ignore list.

Would be great to get this fixed though- normal clicking of items to remove them should be the standard behavior.

**Comment by fernandoval** [comment]
Defining the preserveSelected option as false the click at selected options or the button select none does the unselection.

But the selectpicker('deselectAll') method don't.

I fixed this with this two lines:

```
            $('#filter-seller_id option').attr('selected', false);
            $('#filter-seller_id').selectpicker('refresh');
```

**Comment by razvan-theodor** [comment]
+1

**Comment by andrius-senulis** [comment]
@fernandoval, I assume that you have your two lines in the `changed.bs.select` event? Otherwise, could you please explain?

**Comment by fernandoval** [comment]
My code:

```
        $('#filter-listing_id').selectpicker({
            actionsBox: true,
            liveSearch: true,
            style: 'btn-default flat'
        }).ajaxSelectPicker({
            ajax: {
                url: '/rest/listings',
                type: 'GET',
                data: function () {
                    var params = {
                        filter: {
                            name: '{{{q}}}'
                        }
                    };
                    return params;
                }
            },
            preprocessData: function (result) {
                var listings = [];

                $.each(result.data, function (idx, row) {
                    listings.push(
                        {
                            value: row.id,
                            text: row.name,
                            disabled: false
                        }
                    );
                });
                return listings;
            },
            preserveSelected: true
        });
```

Only this.

**Comment by fernandoval** [comment]
And this. In other program with same issue.

```
        $('#filter-seller_id').selectpicker({
            actionsBox: true,
            liveSearch: true,
            style: 'btn-default flat'
        }).ajaxSelectPicker({
            ajax: {
                url: '/rest/sellers',
                type: 'GET',
                data: function () {
                    var params = {
                        filter: {
                            name: '{{{q}}}'
                        }
                    };
                    return params;
                }
            },
            preprocessData: function (result) {
                var sellers = [];

                $.each(result.data, function (idx, row) {
                    sellers.push(
                        {
                            value: row.id,
                            text: row.name,
                            disabled: false
                        }
                    );
                });
                return sellers;
            },
            preserveSelected: false
        });
```

**Comment by andrius-senulis** [comment]
@fernandoval, it doesn't help me to solve the issue. I have this already. The problem is that the plugin does not deselect the options on click when the `preserveSelected: true` is set.

**Comment by jengjeng** [comment]
I have fixed this issue by clean the cache object with this code
`// Use after init select picker`
`$('.select-picker').data('AjaxBootstrapSelect').list.cache = {}`

You can try from this fiddle https://jsfiddle.net/a3ybhne4/9/

**Comment by mattfeury** [comment]
seeing this as well. will try some workarounds but this definitely seems like a bug

**Comment by pudjamansyurin** [comment]
wow, there's still no fix for this?

**Comment by capcom-r** [comment]
@jengjeng Thanks so much dude, works great for selects with the "multiple" attribute. Doesn't work for standard single select menus. Any thoughts? Thanks again.

**Comment by markcarver** [comment]
Sounds like a dup of #164
