### ISSUE TITLE
Laravel 5.2 value of the search query

### ISSUE THREAD

**Issue by hybrid1969** [truckingsim/Ajax-Bootstrap-Select#95]
Is there way to access the value of the search query directly in stead of using the {{{q}}} option is this does not work with Laravel 5.2 blade templates.

**Comment by hybrid1969** [comment]
So far i have got it working if a put set value in but for the life of me do not seem to be able to access the search box input text. I know its something glaringly obvious but I just cant see it.

`$('#addSystems #system').selectpicker({
        liveSearch: true,
        bindEvent: 'keyup paste'
    }).ajaxSelectPicker({
        ajaxOptions: {
            url: '/sys-l',
            type: 'GET',
            dataType: 'json',
            headers: {
                'X-CSRF-Token': $('#_token').val(),
            },
            data: function () {
                var params = {
                    system:  $('#addSystems #system').selectpicker().find('.bs-searchbox input').val()
                };
                return params;
            },
            beforeSend: function (xhr, opts) {
                if ($('#addSystems #system').selectpicker().find('.bs-searchbox input').val() < 3){
                    xhr.abort ();
                }
            }
            },
            emptyRequest: true,
            locale: {
                emptyTitle: 'Search for system...'
            },
            preprocessData: function(data){
                return data;
            },
            preserveSelected: false
        });`

**Comment by truckingsim** [comment]
@hybrid1969 try:

```js
$('#addSystems #system).data().selectpicker.$searchbox.val();
```

**Comment by hybrid1969** [comment]
That was it, very much appreciated. 

I hate code blindness.
