### ISSUE TITLE
Minimum length search criteria before ajax

### ISSUE THREAD

**Issue by tihiz** [truckingsim/Ajax-Bootstrap-Select#98]
**Dear truckingsim,**

First of all I like this plugin very much.
I implemented a new, small functionality to my version, and I tought you shoud consider to make it available in your release also. 

I faced that my users types very slow. In case of you have a big data source and the user is pressing only one letter within the timeout period,  a huge a amount of data will be loaded. (it is very slow)

I created an option that calls the ajax request only after "n" charasters was entered. 
By this way I am able to keep the fast and user friendly functionality.

**Best regards**

**Comment by truckingsim** [comment]
Also the full build process is broken on all my computers.  That's another reason I haven't done a merge on this because I can't update the documentation right now.

**Comment by PhilPJL** [comment]
@tihiz It's quite simple to apply the min chars restriction on the server, the only thing you don't get is a nice message like 'More chars required'.
